# Site settings
baseurl = "https://unconventional.co/"
languageCode = "en-us"
title = "Think Different"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-41070069-1"
# Disable comments by leaving disqusShortname empty
disqusShortname = "unconventionalco"

[params]
  name = "Bryan Wong"
  description = "Everyone is born a genius; it is the art of perception that molds us to be who we are"
  bio = "Investment | Business | Wisdom"
  # Enter optionally your twitter account
  twitter = "bryanwongbh"
  enableRSS = true

  # Add custom assets with their paths relative to the static folder
  customCSS = []
  customJS  = []

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.

  # Navigation links
  home = ""
  about = ""
  books = ""
  subscribe = ""
  # Pagination links
  olderPosts = "Previous Post"
  newerPosts = "Next Post"
  readMore = ""
  copyright = ""
  # Sharing options and author information in posts
  aboutAuthor = "I enjoy finance, business, and stoicism."
  tweet = ""
  share = ""
  # 404 page
  title404 = ""
  subtitle404 = ""

  # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
  iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/bryanwongbh"
    githubalt   = "https://www.github.com/bryanwongbh"
    stackoverflow = "https://stackoverflow.com/users/2605609/bryan-wong"
    linkedin = "https://www.linkedin.com/in/bryanwongbh"
    email = "mailto:bryanwongbh@gmail.com"